### ISSUE TITLE
[fr] ConnectToServerView: potential improvements

### ISSUE THREAD

**Issue by heitbaum** [jellyfin/Swiftfin#104]
Some feedback (nice to haves)
- remember the last server(s)
- Allow mDNS aka. abc.local
- Help text?

**Comment by acvigue** [comment]
1 - app only supports one server, technically no reason to have this.
2 - mDNS? why not use normal DNS.
3 - what exactly, I'd be open to adding this in but I don't know where :p

**Comment by acvigue** [comment]
are these still relevant features?

**Comment by LePips** [comment]
1 - I support the work for multiple servers down the road. Remembering servers can be something discussed then.
2 - mDNS is actually supported because, technically, that's on the LAN/router level and not with the app.
3 - I have ideas for this, will be addressed elsewhere.

This issue can be closed.
