### ISSUE TITLE
Some Obvious Bugs

### ISSUE THREAD

**Issue by tobylibo** [jellyfin/Swiftfin#1242]
No bugs, great app.

**Comment by chickdan** [comment]
> The UI has a lot of untranslated content.

[Here is the Weblate](https://translate.jellyfin.org/projects/swiftfin/) link to contribute translations that you see are missing.

As for the bugs: iOS 18 just release a week ago, it takes time to identify and fix the bugs. Especially since some of them are not "obvious" like you state. I've come across very little of what you've listed aside from the screen rotation which I think is currently intentionally disabled for iPhone.

Most importantly, all of Jellyfin is made for free by people working in their spare time. Sometimes life gets in the way so I highly suggest you either practice your patience or you contribute back to the project in some way.

Suggestion: be a little less condescending when everyone building this can say "no" and just stop building the project.

**Comment by LePips** [comment]
- Translations are always ongoing but actually a good issue since there actually are many strings that don't have localization.
- The rotation, or lack thereof for portrait on iOS, is a deliberate design choice at the moment.
