### ISSUE TITLE
The search results are incomplete

### ISSUE THREAD

**Issue by tobylibo** [jellyfin/Swiftfin#1248]
### Describe the bug

The search results are incomplete，only 20 results are displayed for each search result.

For example, I have 3000 videos, and there are a total of 150 videos with "keyword" in the video name.

But after searching for "keyword", only 20 videos are displayed.

Or am I using the search method incorrectly?

### Application version

1.2 (4)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 Pro

### OS version

iOS 18.0

### Jellyfin server version

10.10.0

**Comment by LePips** [comment]
It is currently a deliberate design to only fetch 20 of each type of media to help a bit with performance, mainly for UI reasons. I have a `TODO` to potentially allow full pagination of types of items. At least, I think we can do so because we get indices in the response that we can start from for pages. Once I figure out something better for the UI we can request more than 20 at a time along with the pagination.

- https://github.com/jellyfin/Swiftfin/blob/071a1f98e14ac1920a9e8e98c00bb36995368479/Swiftfin/Views/SearchView.swift#L13
