### ISSUE TITLE
Apple TV display content in incorrect folder

### ISSUE THREAD

**Issue by swgamerx** [jellyfin/Swiftfin#1317]
On my jellyfish the server, I have three media types, television, movies, and other. Each of these media types are fed from separate folders on NAS, television display is fine, but the movie folder displays videos contained within the other media type, swift on iOS and regular Jellyfin applications show all media correctly, it's just SwiftFin for Apple TV, which displays incorrectly. I've attached a photo of my TV screen showing incorrect files being displayed under movies.

Version 1.01

![image](https://github.com/user-attachments/assets/4eee6f83-d00b-401b-be84-3ea119ffe200)

**Comment by JPKribs** [comment]
Would you be able to validate that the media is correct in the Media section of tvOS?

On iOS, we only use the libraries as options. On tvOS, these two sections are based on type. So, anything with the Movie or Show type will appear in their respective sections. Libraries can be found in the Media section containing all media per Library instead.

If this you are able to see items in their appropriate media library folder, this is working as intended with the request to filter these media types available here:

https://github.com/jellyfin/Swiftfin/issues/1315

**Comment by swgamerx** [comment]
If I go to Media->Movies everything is fine, but if I go to just Movies then it exhibits the reported issue.

**Comment by LePips** [comment]
Like @JPKribs mentioned, on tvOS that section is based on the type of media, which in this case is movies. This isn't using your library called `Movies`, which is understandably confusing. At least currently, there isn't a way to include or exclude multiple libraries, only the ability to include one.

The API would have to be changed in order to accommodate that, and on our end I consider this part of the larger effort of #1034 for customizable tabs.
