### ISSUE TITLE
Testflight iOS 14

### ISSUE THREAD

**Issue by 9p4** [jellyfin/Swiftfin#179]
**Describe the feature you'd like**

Allow the latest Testflight build to run on older versions of iOS.

**Additional context**

Currently, the Testflight build (1.0.0(84)) is only available for iOS 15. If this build could also be made available for iOS 12-14, that would be wonderful.

**Comment by LePips** [comment]
We've deliberately made the decision for iOS 15 because of some Swift 5.5 features that we've implemented. Because Apple has gone a weird route and allowed iOS 15 update to be purely optional with them still supporting iOS 14(.8) it's put developers into a pickle and many in the community to just support iOS 15 since it's supported on so many devices.

I don't even think we could do anything prior to iOS 14 even if we wanted to because of Swift and we don't have a build for those versions of iOS to refer back to.

**Comment by LePips** [comment]
If I recall correctly from my community discussions, some things are backwards compatible with iOS 14. We _could_ investigate supporting iOS 14 with Swift 5.5 but don't get hopes up. I'll take a quick look when I have time.

**Comment by sambhavsaggi** [comment]
Wonderful! Thanks for the prompt response!

**Comment by LePips** [comment]
That is true but then we could use preprocessor flags everywhere for features which doesn't become scalable. Imo it isn't much to ask to use the latest major version of iOS especially nowadays with the culture of iOS 15 supporting so many devices. My argument is more of a laziness argument, I admit. I don't want to go everywhere and put the preprocessor flags where features aren't supported because it puts more work on us to _find where it's crashing at runtime_ and then _add the flag_ and then _release the fix_.

**Comment by LePips** [comment]
Yeah, more specifically that discussion will be around iOS 15 and 16. We'll probably release before iOS 16 releases so there will be both a 15 and 16 version available on the App Store.
