### ISSUE TITLE
iOS - Collections / TMDb Box Sets Plugin

### ISSUE THREAD

**Issue by cheetashock** [jellyfin/Swiftfin#210]
### Describe the bug

When there are movies in a collection, the movies are inaccessible from the collection.
![9849DE52-62AF-4266-9F6C-305227CBEFF6](https://user-images.githubusercontent.com/1431563/140098715-3f053b35-07f0-4216-a45e-43895e1f5c46.png)

### Application version

1.0.0 (66)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 Pro

### OS version

iOS 15.1

### Jellyfin server version

10.7.2

**Comment by LePips** [comment]
Related: https://github.com/jellyfin/Swiftfin/issues/175

But won't mark as duplicate.

**Comment by LePips** [comment]
Actually, this looks like an entire feature request.

**Comment by cheetashock** [comment]
I can access the movies by searching still.

**Comment by LePips** [comment]
Yeah, so it's related to https://github.com/jellyfin/Swiftfin/issues/175 because of the items not shown but that's in the `Library` view, whereas this one is a collection.

I haven't done collections in Jellyfin, would you mind sharing what your setup looks like to create these collections? Or, point me to an example of how collections are created?

**Comment by cheetashock** [comment]
I use the tmdbboxsets plugin to automatically create them.

**Comment by LePips** [comment]
Ah there we go, it's a plugin. I have ideas on how to implement them but it will be a while.

**Comment by LePips** [comment]
Going to change the issue name to reflect that.
