### ISSUE TITLE
Swiftfin on M1 Macs

### ISSUE THREAD

**Issue by LePips** [jellyfin/Swiftfin#215]
Swiftfin can currently run on M1 Macs via TestFlight for Mac. While this is a capability of the project, this **_will not_** be actively developed for and no issues will be accepted regarding the functionality of Swiftfin in this way.

The current goal for Swiftfin is to develop an iOS and tvOS client. After this goal is readily met, the development of Swiftfin towards a macOS client may be addressed. If anything, we may want the client to mirror the tvOS client instead of the iOS client.

**Comment by AyrtonB** [comment]
Is there any update on this?

**Comment by belthesar** [comment]
Heya! It appears that both the Swiftfin releases on the App Store and in TestFlight have been marked as restricted to iOS, iPadOS and tvOS. It may be worthwhile to update the pinned issue to amend the instructions that install on macOS with TestFlight is no longer a viable, even if unsupported, option. Thanks!

**Comment by celarye** [comment]
@belthesar I made separate issue about the TestFlight restriction a while back: https://github.com/jellyfin/Swiftfin/issues/1627

I'll add a comment there mentioning this restriction also extends to the App Store release.

**Comment by MikeRich88** [comment]
https://developer.apple.com/help/app-store-connect/manage-your-apps-availability/manage-availability-of-iphone-and-ipad-apps-on-macs-with-apple-silicon/ Have you looked at this?

The only one who can fix this problem is "Anthony Lavado" in their Apple Developer Account or whatever. I think (Anthony) should try disallowing and then reallowing the app to run on macOS.

**Comment by LePips** [comment]
With new improvements to the overall app's architecture, I will soon be investigating a native Mac app.
