### ISSUE TITLE
H.265 HEVC playback Issues

### ISSUE THREAD

**Issue by thadrumr** [jellyfin/Swiftfin#340]
I am having issues playing back a 1080P HEVC h.265 movie on a Apple TV 4th gen.  I tested it direct plays just fine using the Plex app but Swiftfin doesn't play.  If it does play it has pixelation and slow playback.  The Apple TV has the latest IOS 15 on it and my server is running 10.7.7.

**Comment by LePips** [comment]
Is this a transcoded stream?

**Comment by thadrumr** [comment]
No when it is playing I pull up the admin dashboard and it is direct playing.  I have the app set to force direct play.

**Comment by LePips** [comment]
Okay and thank you, then it's a poor thing that we can only blame on VLCKit. Due to you opening this issue (and it's one of many regarding VLCKit playback) I'm reopening and going to give more focus to: https://github.com/jellyfin/Swiftfin/issues/221

Plex uses mpv.

I will close this as this is something we cannot fix ourselves and is now directed towards that mpv implementation.

**Comment by LePips** [comment]
Just to kind of check out something else, what's the bitrate of your video?

**Comment by thadrumr** [comment]
For what its worth I installed VLC on my Apple TV and it also played fine there as well.  Below is the stats of the movie.

Video
Title1080p HEVC SDR
CodecHEVC
ProfileMain 10
Level120
Resolution1920x800
Aspect ratio2.40:1
InterlacedNo
Framerate23.976025
Bitrate9932 kbps
Video rangeSDR
Color spacebt709
Color transferbt709
Color primariesbt709
Pixel formatyuv420p10le
Ref frames1

**Comment by LePips** [comment]
VLC does use a different version of libvlc which VLCKit I believe hasn't updated in ages. We should expect many improvements with VLCKit v4 or I can maybe try out an unstable version soon
