### ISSUE TITLE
double tap skip causes freezing UI

### ISSUE THREAD

**Issue by eightsheep67** [jellyfin/Swiftfin#427]
### Describe the bug

double tap skip causes freezing UI, and need 2s to recover.
I hope next build can go back to swipe gesture, more efficient.

### Application version

1.0.0 (75)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 mini

### OS version

15.4.1

### Jellyfin server version

10.7.7

**Comment by PangMo5** [comment]
In fact, UI gestures are recovered in 1 second after double-tap.
In order to minimize the impact on UX, if you tap it during recovery, the tap gesture will be executed immediately after recovery.

This is pretty much the same condition as YouTube, and I don't think there will be a big problem
And Personally, I don't think swipe gestures suit the video player.

Instead additional, I'll develop a function that can adjust the slider value with pan gesture when I have time.

**Comment by PangMo5** [comment]
Apart from this problem, there seems to be a UI freezing problem after double tap in certain situations. I'll try to solve it quickly.

**Comment by lesclaz** [comment]
> ### Describe the bug
> 
> double tap skip causes freezing UI, and need 2s to recover.
> 
> I hope next build can go back to swipe gesture, more efficient.
> 
> ### Application version
> 
> 1.0.0 (75)
> 
> ### Where did you install the app from?
> 
> TestFlight
> 
> ### Device information
> 
> iPhone 12 mini
> 
> ### OS version
> 
> 15.4.1
> 
> ### Jellyfin server version
> 
> 10.7.7

Well, this doesn’t happen to me. I see that it works very well, I don’t see any differences with YouTube in terms of speed.
