### ISSUE TITLE
Request: Milestone for tvOS release

### ISSUE THREAD

**Issue by maghoff** [jellyfin/Swiftfin#478]
**Describe the feature you'd like**
I'd like you to somehow describe how close you are to releasing this to the AppStore for tvOS.

**Additional context**
I'm very eagerly anticipating Swiftfin for tvOS, where there is currently no official Jellyfin client. So I'm wondering how far off that may be :slightly_smiling_face: I realise that it might be so far off that it doesn't really make sense to ask the question yet, but even so I'd like to know that.

Is the intention that Swiftfin will replace the existing Jellyfin client for iPadOS and iOS from day one? Does that mean that Swiftfin won't make it to AppStore for any platform before it reaches feature parity or surpasses the existing client? Would it alternatively make sense to release sooner on tvOS? :thinking: This is just stuff I'm wondering about, but I'm sure you have given it more thought than me :slightly_smiling_face: 

It could make sense to create one or more milestones to allow people to check the progress for any release targets.

(For completeness: I'm already aware of Infuse as well as the option of installing Swiftfin via Testflight, thanks!)

**Comment by LePips** [comment]
We are quite far away from an official release. There are stability and feature developments that need to be done. I have all of these in my head and creating issues for each one would surpass 100 issues easily. Due to the many stability developments needed, creating and tracking milestones is hard on my part.

Swiftfin is not a replacement for the expo iOS app and something like that can only be thought about until every media type is supported, or at least most. I have thought about whether to implement more media types in this single app or make a "Swiftfin" suite of apps for each different media type due to ease of development and expectations of user experience. That is years in the future to think about. Swiftfin will be released as a video playback app first.

Luckily, like you mentioned, the tvOS app is simpler and can be released sooner than the iOS app and I have told the internal team about it but we'll see where everything goes. All development is done in free time for developers so we'll release whenever we feel like it's the right time.

**Comment by LePips** [comment]
Yes and thank you for your interest! If I were to put a timeframe on it it'd be at the end of 2022 at the latest.
