### ISSUE TITLE
Support for Dolby Vision on Apple TV 4K?

### ISSUE THREAD

**Issue by LePips** [jellyfin/Swiftfin#525]
CC: @extraslute

<div type='discussions-op-text'>

<sup>Originally posted by **extraslute** August 10, 2022</sup>
Please bear with me while I am new to .. giving feedback on software. 

Is there any talks of supporting Dolby Vision video on Apple TV 4K through this SwiftFin app? 
Recommended video cards to use for HDR10? 

I just recently got M3U Playlists to start working correctly. I had issues at first but figured out how to get them to play successfully and reliably. I can't thank you guys enough for putting work into the application. I cancelled Plex because of their privacy invasiveness. 

Some bugs I've noticed are: 

- When scrolling through movie library, the scrolling function glitches and forces the list back to the top unless you hold your finger on the touchpad to keep it from jerking to the top. 
- When clicking on HDR movies to play them, the UI doesn't allow you to click on them. It has the click animation when you try to click into the movie but it won't do anything. If I change my video settings under experimental, it will open it but the movies don't play well. (Yes I am using direct connected CAT6, Gigabit Cisco switch and dual 1Gbps connections to the movie server. I've tried single Gig with no change as I thought maybe there was conflict). 

</div>

**Comment by LePips** [comment]
VLCKit does not have support for Dolby Vision and we are working on proper codec support in https://github.com/jellyfin/Swiftfin/pull/519.

Per your bugs:
1 - duplicate of https://github.com/jellyfin/Swiftfin/issues/332. Might not be the exact same issue but these views will be redone anyways.
2 - this doesn't matter whether it's an HDR movie. Could you provide some video per what steps you're taking? This is kind of vague

**Comment by extraslute** [comment]
@LePips 

You may ignore bug #2. 
Somehow it stopped doing it when I went to record a video of it. If this issue occurs again, I will record and post my current settings and then repeat the issue. However, I have a lot of problems playing HDR Content but this is not necessarily your problem. 

Do you have any recommendations for a Video Card I should use to do hardware acceleration for HDR content? Apple TV 4K cannot handle a 60GB HDR video with direct play enabled. It jumps around too much and glitches / has white pixel junk. 

Disabling direct play makes it buffer too much. I assume this is due to me using an unsupported NVIDIA card on Ubuntu to run JELLYFIN Server which is why I ask for recommendation on video card. I was going to purchase a 1060 but wasn't sure if it would work. I saw comments online saying not to even try tone mapping / acceleration. Rather consult the brains behind the scenes than online Reddit threads.

**Comment by LePips** [comment]
[VLC does not support HDR](https://code.videolan.org/videolan/vlc/-/issues/18618) on Apple devices and by extension, VLCKit does not either. You might get luck with the native player but that would require a transcode. Second, I'm not an expert when it comes to the server capabilities so I won't be able to answer anything regarding your card, apologies.
