### ISSUE TITLE
Thumbnail when scrubbing

### ISSUE THREAD

**Issue by PangMo5** [jellyfin/Swiftfin#573]
![image](https://user-images.githubusercontent.com/16532526/189545597-a2193f6e-c5ac-40e6-9bf7-d97b3ff2aacf.png)

It would be nice to have a function that shows the Thumbnails of the ticks when slider scrubbing, such as YouTube or Infuse.

I'm working right now, It seems that it can be implemented to some extent by using [VLCMediaThumbnailer](https://github.com/videolan/vlckit/blob/master/Sources/VLCMediaThumbnailer.m)

I would appreciate it if you could give me any other good opinions on implementation.

The runTimeTicks of the media are applied immediately according to the current `sliderPercentage`, so related modifications are also required.

**Comment by LePips** [comment]
[Jellyscrub](https://github.com/nicknsy/jellyscrub) is the way to go with this functionality. However, I won't be doing plug-in support to prioritize using the official API and it has only been briefly mentioned with the team about incorporating the image functionality into 10.9.

I don't want to depend on VLCKit for any additional functionality it can offer since I'm looking at ripping it out. It will just simply serve for basic video playback.

I will close this since we can't do anything about it, but I am keeping an eye on the hopeful official implementation since this is a very nice feature.
