### ISSUE TITLE
Background play iOS

### ISSUE THREAD

**Issue by jorritsmit** [jellyfin/Swiftfin#618]
I would like to work on background play for iOS, but i read somewhere in the issues that the VLCkit doesn't allow this, but that you might be changing to a different framework.

What are your plans for the video framework and what do you know about the limitations of background play?

**Comment by LePips** [comment]
By "background play" do you mean PiP or just background audio? VLCKit doesn't support PiP, but can do background audio probably fine. I currently pause playback when the app is backgrounded because VLCKit stops drawing then. I will probably make it an option with an explanation so people don't really complain.

Ultimately we need to register our playback with the system, related https://github.com/jellyfin/Swiftfin/issues/565.

I am developing an mpv player and work for any background play must be done there first before here.

**Comment by jorritsmit** [comment]
OK good to know, then working on with the VLCkit is a waste of time. If you want any help on the MPV work let me know

**Comment by leocaseiro** [comment]
Is this feature completed? It doesn't seem to work on the version I am using it. Do I need to enable to have background audio?
