### ISSUE TITLE
TestFlight beta is full

### ISSUE THREAD

**Issue by keithamus** [jellyfin/Swiftfin#628]
**Describe the feature you'd like**

Hello! I’d like to join the TestFlight beta, but it is reporting that it is full. Are there any more available seats?

**Comment by anthonylavado** [comment]
I'm working on it. There's an astonishing number of people who accepted the link or got a manual invite and then never downloaded the app.

**Comment by anthonylavado** [comment]
There should be a couple hundred slots now, if you could please try again.

**Comment by keithamus** [comment]
Thanks @anthonylavado, I've managed to join the testlfight! Should I close this issue? Or perhaps leave it open if others come trying to open one?

**Comment by IchBinGROOT** [comment]
Please do not close the issue, I have the same problem.

**Comment by AlfNeo** [comment]
Hi, just tried today, still says it'a full

**Comment by rursache** [comment]
> There should be a couple hundred slots now, if you could please try again.

it's full again

**Comment by anthonylavado** [comment]
@rursache Thanks for tagging me, I get way too many notifications to check them normally.

I opened up over 400 slots when I wrote that just over a week ago. I've opened about 100 now by deleting some more inactive testers, but I think I'm just going to have to push the incomplete app to the store at this point.

Go ahead and try again now please.

**Comment by rursache** [comment]
thanks a lot! 
i think pushing to appstore is the right way, even if it's still in beta!

**Comment by rachtsingh** [comment]
I think the testflight is full again, unfortunately. I would love to see it on the App Store, even if it doesn't have all the features the developers would like (launch early, as they say). I've heard such great things, I'm excited to see it.

**Comment by vleeuwenmenno** [comment]
Same here, seems to be full. I'd like to test this out.

**Comment by akashrajum7** [comment]
I would also like to try this but beta is full.

**Comment by anthonylavado** [comment]
Hey all, just checking in to say I see all your messages and notes - I know the beta is full and as I've mentioned I already freed up some 500 slots (100 in the last batch), just to see them get snatched up.

I can't possibly keep booting people manually to keep up with demand - TestFlight limits you to 10,000 external users and there's no automated tool for removing inactive users. I have to try and click through a list to find people with low session counts and kick them.

At this point, we're getting ready to submit the unfinished in-progress app to the store so that everyone can get their hands on it. This is holiday time in the US, so Apple's own processing would be slow. I'm resetting my dev environment to take the necessary screenshots and prepare our submission (especially before the next break, Christmas).

I'll ask for your patience at this time so that I can just focus on this instead and get it out the door sooner rather than later.

I'll post another update when there's more to share. If you want to show support,just click the "thumbs up" or whatever reaction, You can also click "Subscribe" on the right if you want to be notified if I post in this issue. I'd ask that you please **do not reply** unless it is **very important**, as it will send a message to everyone following this issue.

**Comment by JDiaz11** [comment]
Hi - the last update was a month ago and pre-christmas was mentioned as far as App Store availability. Is it? I searched for "swiftfin" and no results were returned. Thanks.

**Comment by thornbill** [comment]
This issue will be updated when the status changes. Also https://jellyfin.org/docs/general/faq#when-will-release-x-happen-when-will-feature-x-be-available

**Comment by dani190** [comment]
Looks like the beta is full again

**Comment by anthonylavado** [comment]
Just hang tight about 24 hours or so 😎

**Comment by anthonylavado** [comment]
It's out!
https://jellyfin.org/posts/2022/12/29/swiftfin/

**Comment by 3rand0m** [comment]
Full

**Comment by anthonylavado** [comment]
It's on the store. Check out the link in my comment above.

Locking thread from further comment.
