### ISSUE TITLE
Swiftfin doesn't respect download Mbs limit

### ISSUE THREAD

**Issue by michpas** [jellyfin/Swiftfin#678]
### Describe the bug

1. Goto jellyfin admin /dashboard/users/ set Internet streaming bitrate limit to 2
2. Logout admin. 
3. Login as user / settings / playback  / set home network quality & Chromecast quality to 480p -1.5 mbs
4. Play a 1080p 4+ Mbps video on user in swiftfin
5. Swiftin plays the file at original size (jellyfin states also: Device supports codecs

My expectations is Swiftin to respect the bitrate limit and not stream the original full size file

Use case: Ipad connecting to hotspot from mobilephone, to allow video streaming whilst traveling.

### Application version

1.0.0 (79)

### Where did you install the app from?

App Store

### Device information

Ipad Air 3rd Gen

### OS version

Ios 15.5

### Jellyfin server version

10.8.8

**Comment by shimi-ke** [comment]
I can confirm my experience is the same. But I suspect the problem might be elsewhere (probably on a server). I think so because I have the same experience not only with Swiftin but with Infuse Pro as well. Both applications seem to ignore playback settings set on server.

When I tried to inspect logs on my jellyfin server I found out that the RemoteClientBitrateLimit is set correctly but the play_method is set to "DirectPlay" even if the bitrate exceeds the RemoteClientBitrateLimit. If I use the same profile but Jellyfin iOS app, the RemoteClientBitrateLimit is set correctly and the play method is "Transcode", which is intended behavior.

All applications are the latest versions and have been downloaded from the AppStore. I use them on my iPhone running iOS 16.2.

Jellyfin server is 10.8.8.

**Comment by LePips** [comment]
I do believe this would be a server issue as clients make a request for the streaming url. If transcoding is required, like in the event of server-set bitrate maximums, clients will (or should at least) use it.

**Comment by Cloudcatcher888** [comment]
exactly same experience with @shimi-ke and @michpas using Infuse Pro and Swiftfin with a frp server (8Mbps)

**Comment by luyvlei** [comment]
In my experience, the jellyfin use client cookies to control the default bitrate limit. When I clean the cookies of my chrome after change the default bitrate limit to 10Mbps, the bitrate limite will be reset to 'auto'. When a new device, e.g. swiftfin, login the server, the default bitrate limit will also be 'auto'. 

For any new device login the server, the bitrate limit will be 'auto'. So I think the swiftfin app should have a menu to change the default bitrate and the bitrate limit will work for this device since there is no menu to control the bitrate when playing the video, which is different from the the html version of the jellyfin client.

**Comment by GravitySandwich** [comment]
I still the same issue on 10.8.10 and the latest swiftfin. Does not matter what device or network (iPadOS, iPhone, apple TV) I use. This makes playing blu-rays or any 4k content outside of my home network unusable.

**Comment by ShadowJonathan** [comment]
I'm having this issue constantly with the latest versions across all my devices, this is preventing me from installing and/or recommending jellyfin to others, since we have a very poor upload speed, and clients constantly try to cram the direct play bit rate (often over 20Mbps) into our ADSL upload speed (4-5 Mbps), even when I set a global limit of 4 Mbps, which then isn't picked up on.

**Comment by ShadowJonathan** [comment]
Related to https://github.com/jellyfin/Swiftfin/issues/184; Swiftfin doesn't appear to support quality profiles at the moment.

**Comment by ShadowJonathan** [comment]
I found this line of code;

https://github.com/jellyfin/Swiftfin/blob/eb17300061315ff310749871f5b79032385ba55a/Shared/Extensions/JellyfinAPI/BaseItemDto%2BVideoPlayerViewModel.swift#L21C26-L21C26

**Comment by ShadowJonathan** [comment]
I also found related code which causes the app to prefer direct play over transcoding (and reducing bandwidth)

**Comment by WolframCrem** [comment]
> I also found related code which causes the app to prefer direct play over transcoding (and reducing bandwidth)

Mind saying where exactly ?

**Comment by jackhric** [comment]
Any update to this issue? This is the only thing holding me back from using Swiftfin permanently inside and outside of the house.

**Comment by WolframCrem** [comment]
@jackhric i'm working on a pr which will somewhat implement resolution for the max bit rate /Mbps

**Comment by jackhric** [comment]
@WolframCrem Awesome. Looking forward to it.
