### ISSUE TITLE
[Feature Request] Support for Jellyscrub

### ISSUE THREAD

**Issue by arjunsrinivasan1997** [jellyfin/Swiftfin#713]
**Describe the feature you'd like**

[Jellyscrub](https://github.com/nicknsy/jellyscrub) generates scrubbing image preview files and is currently supported on the official iOS app. I would like for swiftfin to be able to support and displays these image previews.
**Additional context**

![IMG_5408](https://user-images.githubusercontent.com/25167567/222242021-9db721c8-fa62-42bd-9205-a6144fbfa7e4.PNG)

**Comment by thornbill** [comment]
Support for this will not be added to official apps until the feature is supported directly by the Jellyfin server. This is to avoid plugin changes potentially breaking apps or conflicting with an official implementation. It only works in the main iOS app due to it reusing the web interface for most of its ui.
