### ISSUE TITLE
Music Video’s

### ISSUE THREAD

**Issue by papadeeh** [jellyfin/Swiftfin#727]
After installing Swiftfin on an AppleTV 4, yesterday, I found my Musicvideo library is not shown. 
Although I understand that plain music is not part of Swiftfin, I would expect that Music video’s like videoclips or complete concerts would be shown.

Am I wrong to assume this?

If this is (for now) regular behaviour, then I would like to request that this category of files is included in Swiftfin.

Besides this I have not found a fault till this moment (when using the native video player because of the lack of multichannel audio support in the standard video player)

Regards,

**Comment by Superdurt** [comment]
I have found out that adding the library with the Movie content type, does show the videos then. You can use it as a workout untill a proper fix.

**Comment by maikvitesse** [comment]
Thanks for the workaround @Superdurt 
Hope this is fixed soon!

**Comment by ziqizh** [comment]
Hi, are there any updates on the music videos?

**Comment by LePips** [comment]
The reason why I had kept this open was because it isn't technically difficult to implement music videos, however I would only really get to this in the first place when implementing music so that views have good data and are linked properly.

I will defer this to when I get to music, as right now we are only focused on movies/series.
