### ISSUE TITLE
please make "Swiftfin" also available in the Mac App Store for Apple Silicon Macs

### ISSUE THREAD

**Issue by GETandSELECT** [jellyfin/Swiftfin#732]
I have an Apple silicon Mac. I can use almost all iOS apps on it.
But Swiftfin is not, it was not released for the Mac App Store, it seems.

I like Swiftfin very much (on tvOS and iPhone), I like it much better than the classic iOS app.

Please release Swiftfin for macOS too.

best thanks and greetings

**Comment by LePips** [comment]
Please see the pinned issue: #215

**Comment by gartunius** [comment]
@LePips but can it be made available on the mac app store on "Iphone & Ipad Apps" section? because I think that way it's a "one time" thing for you guys and we can get something. Also because the Test Flight(at least the last time I tried) was full, and now that the app has released I don't think we can get into it anymore.

**Comment by bandundu** [comment]
Any update on this available? Would be amazing

**Comment by kiwinh0** [comment]
another more interested in development. It would be very nice to have the version for MacOS even without being available in the store. Being MacOS we could install it directly. Thank you
