### ISSUE TITLE
Swiftfin AppleTV + Stereo Homepods Audio Delay

### ISSUE THREAD

**Issue by mvonwismar** [jellyfin/Swiftfin#734]
### Describe the bug

Audio is lagging by seconds when using a Homepod mini pair with 2nd gen Apple TV 4K. This is the only app that has a delay like this on my apple TV. Even when I play something and exit the app, the audio still plays for a few seconds, I switched to tv audio and the issue disappeared (though obviously the audio is much worse) 

### Application version

1.0.1

### Where did you install the app from?

None

### Device information

Apple TV 4K (2nd Generation)

### OS version

tvOS 16.3.3

### Jellyfin server version

10.8.9

**Comment by anujdeshpande** [comment]
Same - happy to help debug!

**Comment by LePips** [comment]
Sadly, this is a limitation of VLCKit and nothing that we can do about it. However, if those calibration settings do help, I may link it shortly in an issue I will create soon regarding playback shortcomings.

**Comment by overdrive31** [comment]
Funny they label it as Wireless Audio Sync. It defaults to the TV Speakers for each Calibration and the audio lag is still in Swiftfin. Why will it not Calibrate the HomePod’s? Guess it will never get fixed.

**Comment by robgjansen** [comment]
I believe that the Apple calibration procedure uses the TV speakers _and_ the Homepod microphones during calibration to help the Homepod learn the latency between the TV audio path and the Homepod audio path. So I think it is indeed doing what we want it to be doing.

I think the problem here is that when Swiftfin does not use the native Apple video player (which is well calibrated), then it does not automatically get the Apple TV OS-provided calibration. Ie., the VLCKit video player that Swiftfin uses would need to have its own calibration procedure which I'm guessing it does not. I think Swiftfin does have an experimental setting to force it to use the Native Apple video player, but using it can significantly degrade video quality.

**Comment by overdrive31** [comment]
When issuing the Calibration, it actually uses my iPhone’s Microphone to do the listening. The HomePod’s are never involved in the Calibration despite being the default audio output.

**Comment by Phaired** [comment]
Actually having the same issue, however using Infuse the audio seems to be perfectly synchronized.

**Comment by shi-vy** [comment]
Just +1'ing that I also have this issue.  Will give it a go with that experimental feature.

**Comment by SteveHan-233** [comment]
Same issue here. Other apps like YouTube have no delay whatsoever (if you press play, the audio starts immediately).

**Comment by robgjansen** [comment]
I'm disappointed that the fix seems to be "we can't/won't fix it, go use infuse instead". There are many reasons why Swiftfin is preferred. Are there viable alternatives to VLCKit (e.g., the native player?) that could help?

**Comment by anujdeshpande** [comment]
Fwiw changing to the native player from settings worked well for me. Didn't have to move to infuse.

**Comment by SteveHan-233** [comment]
The native player doesn’t work for me at all. I’m using vp9 codec.

**Comment by smellslikemoose** [comment]
Same issue here, using Apple TV + HomePods. Switching to the experimental native player fixes the audio but I lose video in most cases.

**Comment by davilaa** [comment]
I’m having this problem too on the latest version. Is there a plan to fix this? I see its been closed without resolution.

**Comment by 8bitreid** [comment]
Same issue here. Also the native player doesn't work for me on Apple TV.

**Comment by RubyMetro** [comment]
Just wanted to +1 this, can’t move to infuse because it’s paid to use jellyfin servers.

**Comment by ReindDooyeweerd** [comment]
Same issue here, tried the native player and that fixes the issue BUT then my subtitles won't work. Pity though because i like Swiftfin more than Infuse to be honest.

**Comment by kiwinh0** [comment]
Another one that joins the group. Same problem and using the native player solves the problem but creates others. For now I have also had to temporarily switch to Infuse. It's a shame because until now Jellyfin was a very promising project to surpass Plex, but with these problems in its clients, a large number of users will think again.
It's a shame I really like Jellyfin, but supporting a project that doesn't think about users is a waste of time.

**Comment by ReindDooyeweerd** [comment]
> Sadly, this is a limitation of VLCKit and nothing that we can do about it. However, if those calibration settings do help, I may link it shortly in an issue I will create soon regarding playback shortcomings.

Any chance this is solved with the new version? Is saw some mentions about an update of VLC kit in other topics.

**Comment by BitWise-0x** [comment]
issue still open on AppleTV? Native player does seem to correct issue but adds other nuances...  

I am also using a pair of HomePods paired as stereo speakers with my Apple TV

**Comment by ReindDooyeweerd** [comment]
> issue still open on AppleTV? Native player does seem to correct issue but adds other nuances...
> 
> I am also using a pair of HomePods paired as stereo speakers with my Apple TV

Yes it is. There doesn’t seem to be much progress on this, I doubt it’s still on the radar. It annoyed me that much that I switched back to Plex recently.

**Comment by aca626** [comment]
> issue still open on AppleTV? Native player does seem to correct issue but adds other nuances...
> 
> I am also using a pair of HomePods paired as stereo speakers with my Apple TV

Native Player does indeed resolve the latency issue but disables all controls regarding subtitles and audio channels.

I found a workaround by using the jellyfin web app on my iPhone and airplaying the chosen video to my Apple TV. It uses the native player on the Apple TV with all its glorious audio calibration, while you still can change settings regarding audio, subtitles and chapter selection in the web app on your iPhone.

An advantage of this solution is, that you don’t need an extra app neither on your iPhone nor your Apple TV. 

It has to be noted though, that Airplay only supports videos up to 1080p, as far as I know.

**Comment by 8bitreid** [comment]
> > issue still open on AppleTV? Native player does seem to correct issue but adds other nuances...
> > 
> > I am also using a pair of HomePods paired as stereo speakers with my Apple TV
> 
> Native Player does indeed resolve the latency issue but disables all controls regarding subtitles and audio channels.
> 
> I found a workaround by using the jellyfin web app on my iPhone and airplaying the chosen video to my Apple TV. It uses the native player on the Apple TV with all its glorious audio calibration, while you still can change settings regarding audio, subtitles and chapter selection in the web app on your iPhone.
> 
> An advantage of this solution is, that you don’t need an extra app neither on your iPhone nor your Apple TV. 
> 
> It has to be noted though, that Airplay only supports videos up to 1080p, as far as I know.

This is a really not ideal workaround. I'd like to know if Jellyfin or Swiftfin plan to fix this. I mean - it's forcing me to pay for Infuse. Infuse is great, but the selection of movies on Jellyfin are better.

**Comment by JPKribs** [comment]
Hi All, 

I just wanted to hop in here since I saw it was recently active. Unfortunately, this issue is on the VLCKit side. The reason this item is 'resolved' for Swiftfin, is because we are not able to do anything about this while still using VLCKit. You can find VLC's issue for their progress here: https://code.videolan.org/videolan/VLCKit/-/issues/544.

If VLC releases a fix for this as part of their next stable release, we will be sure to update this on our end to take advantage of it. At this time, we are using the latest stable release (3.6) where the issue is still present. Following this on the VLCKit side, I haven't seen anything on their end that suggests that this is resolved in their beta 4.0 release.

From our end, as Swiftfin, there is a great PR in the works to improve our playback manager here: https://github.com/jellyfin/Swiftfin/pull/1203. While I cannot promise this will resolve all of our issues, this should greatly improve playback in general with Swiftfin and should make Native Player better to use as well.

Already, in our Main Branch, we have https://github.com/jellyfin/Swiftfin/pull/519 which improves Swiftfin's ability to detect playback requirements and transcode if necessary. This will be included in our next release and should improve using the Native Player on tvOS dramatically. This should prevent playback issues on tvOS where the Native Player fails to start playback due to incompatible files and correctly request a transcode from the server.

The goal is for both of these items to be included in our next tvOS release. You can follow the progress for our next tvOS release here: https://github.com/jellyfin/Swiftfin/discussions/1294

Finally, we do have an open item to work on MPV here: https://github.com/jellyfin/Swiftfin/issues/221. This item is a lot further away as the Playback Manager and some other items would need to come first. I would consider #221 more of a 'someday' but just to put it on the radar. 

Sorry, I'm not able to share any better news but unless _(until?)_ we start building our own player, we are at the mercy of other projects and their teams. Hopefully, we see some progress related to this on the VLC side! That being said, **please be respectful of the VLC devs as well**. Many of them are FOSS volunteers as well who are working hard to provide a free tool for all of us.

**Comment by juxuanu** [comment]
Just wondering, is there no Apple method to query the OS for the audio delay and then apply that to the VLC player for the current sound track (or delay the start of the video)?
