### ISSUE TITLE
Getting Error “-1,001 Network timed out”

### ISSUE THREAD

**Issue by iamronr** [jellyfin/Swiftfin#797]
### Describe the bug

I successfully log into the JellyFin server. When it goes to fetch the content I get the above mentioned error code.

Tested on JellyFin mobile app and it works perfectly fine. Everything loads. But SwiftFin isn’t. 
![IMG_2121](https://github.com/jellyfin/Swiftfin/assets/698319/5f94ffd6-81b3-41a4-ba87-caa9e5540c0d)

Here’s the same content in the JellyFin app
![IMG_2124](https://github.com/jellyfin/Swiftfin/assets/698319/dcfc11b3-005b-4012-bc0d-fdb513057cef)

### Application version

1.0.1 (70)

### Where did you install the app from?

App Store

### Device information

iPhone 13 Pro and Apple TV

### OS version

iOS & tvOS Beta 2

### Jellyfin server version

10.8.10

**Comment by LePips** [comment]
Are you connected to the right protocol, `http/https`?

**Comment by Snuggle** [comment]
Same issue just started happening to me! I connect via an NGINX/LetsEncrypt reverse proxy using exclusively HTTPS.

I only recently updated Jellyfin and it seems to have been broken since around that same time.

Using Apple TV 4K Gen 1 model A1842 (32 GB) with tvOS 16.5 (20L563)
Jellyfin Version: 10.8.10
Swiftfin Version: 1.0.1 (70)

**Comment by dmt816** [comment]
Can confirm, same issue here with the Swiftfin app on both iPhone (13 Pro) and Apple TV (4K 1st Gen)
Happy to provide whatever info I can.

**Comment by LePips** [comment]
I forgot to grab this in #1045 as there has been better error handling and surfacing.
