### ISSUE TITLE
Cannot connect to local server from AppleTV 4K

### ISSUE THREAD

**Issue by kdbruin** [jellyfin/Swiftfin#959]
### Describe the bug

Installed it from the AppStore on my AppleTV 4K but I cannot connect to my local server. However, I can connect to the same server using my iPad.

### Application version

1.0.1

### Where did you install the app from?

App Store

### Device information

AppleTV 4K, 128GB

### OS version

tvOS 17.3

### Jellyfin server version

10.8.13

**Comment by AndreiGhiurea** [comment]
Are you sure the link it find automatically is correct? For example, for me, the app (on both tvOS and iOS) finds a local server with the url `https://example.com` and it won't connect because the actual url for me is `https://example.com/jelly`. Granted, the iOS version throws an error message, but on tvOS it fails silently.

Took me a while to figure this out.

**Comment by electronaught** [comment]
bumping this issue as I'm also experiencing this problem.  

**Describe the bug**

Exactly like OP's: Installed Swiftfin from the AppStore on my AppleTV 4K.  My local jellyfin server is discoverable (correct IP and port number) but selecting it does nothing.   I can connect to the same server on other devices:  phone, laptop, and other TV.

No change in behavior if trying to connect over ethernet or wifi. 

**Application version**

1.0.1

**Where did you install the app from?**

App Store

**Device information**

AppleTV 4K, 128GB

**OS version**

tvOS 18.2 [22k155]

**Jellyfin server version**

10.10.3
